# Generated by Django 5.2.4 on 2025-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale_product_slug_supplier_products_supplier_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='inventory.supplier'),
        ),
    ]
