# Generated by Django 5.2.4 on 2025-07-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_supplier_products_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_itmes',
        ),
    ]
